version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: always
    networks:
      - campus-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/test"]
      interval: 20s
      timeout: 5s
      retries: 5

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      server:
        condition: service_healthy
    restart: always
    networks:
      - campus-net

networks:
  campus-net:
    driver: bridge
