apiVersion: v1
kind: Secret
metadata:
  name: campus-secrets
type: Opaque
stringData:
  PORT: "5000"
  MONGO_URI: "mongodb+srv://<username>:<password>@cluster0.mongodb.net/campusDB?retryWrites=true&w=majority"
  JWT_SECRET: "your_jwt_secret_here"
  EMAIL_USER: "your.email@gmail.com"
  EMAIL_PASS: "your_app_password"
  ADMIN_EMAIL: "admin@msrit.edu"
  ADMIN_PASSWORD: "admin123"
